//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int IDAction { get; set; }
        public string Nom { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IDTypeAction { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Valide { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual TypeAction TypeAction { get; set; }
        public virtual User User { get; set; }
    }
}
