//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresseBeneficiaire
    {
        public int IDAdresseBeneficiaire { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
        public Nullable<int> IDAdresse { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Beneficiaire Beneficiaire { get; set; }
    }
}
