//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public Adresse()
        {
            this.AdresseBeneficiaire = new HashSet<AdresseBeneficiaire>();
        }
    
        public int IDAdresse { get; set; }
        public string Ligne1 { get; set; }
        public string Ligne2 { get; set; }
        public string Pays { get; set; }
        public Nullable<int> IDTypeAdresse { get; set; }
        public Nullable<int> IDLocalite { get; set; }
    
        public virtual ICollection<AdresseBeneficiaire> AdresseBeneficiaire { get; set; }
        public virtual Localite Localite { get; set; }
        public virtual TypeAdresse TypeAdresse { get; set; }
    }
}
