//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssistantSocial
    {
        public AssistantSocial()
        {
            this.BeneficiaireProgramme = new HashSet<BeneficiaireProgramme>();
        }
    
        public int IDAssistantSocial { get; set; }
        public Nullable<int> IDUser { get; set; }
    
        public virtual ICollection<BeneficiaireProgramme> BeneficiaireProgramme { get; set; }
        public virtual User User { get; set; }
    }
}
