//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtelierFSE
    {
        public AtelierFSE()
        {
            this.Participation = new HashSet<Participation>();
        }
    
        public int IDAtelierFSE { get; set; }
        public string NomAtelier { get; set; }
        public string CommentairesAtelier { get; set; }
    
        public virtual ICollection<Participation> Participation { get; set; }
    }
}
