//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avocat
    {
        public Avocat()
        {
            this.BeneficiaireAvocat = new HashSet<BeneficiaireAvocat>();
        }
    
        public int AvocatID { get; set; }
        public string AvocatNom { get; set; }
        public string AvocatPrenom { get; set; }
        public string AvocatAdresse1 { get; set; }
        public string AvocatAdresse2 { get; set; }
        public string AvocatCP { get; set; }
        public string Avocatlocalite { get; set; }
        public string AvocatTelephone { get; set; }
        public string AvocatFax { get; set; }
        public string AvocatMail { get; set; }
        public string Commentaires { get; set; }
    
        public virtual ICollection<BeneficiaireAvocat> BeneficiaireAvocat { get; set; }
    }
}
