//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxePsy
    {
        public AxePsy()
        {
            this.Beneficiaire = new HashSet<Beneficiaire>();
            this.Beneficiaire1 = new HashSet<Beneficiaire>();
            this.Beneficiaire2 = new HashSet<Beneficiaire>();
            this.Beneficiaire3 = new HashSet<Beneficiaire>();
            this.Beneficiaire4 = new HashSet<Beneficiaire>();
            this.Beneficiaire5 = new HashSet<Beneficiaire>();
            this.Beneficiaire6 = new HashSet<Beneficiaire>();
            this.Beneficiaire7 = new HashSet<Beneficiaire>();
            this.Beneficiaire8 = new HashSet<Beneficiaire>();
            this.Beneficiaire9 = new HashSet<Beneficiaire>();
            this.Beneficiaire10 = new HashSet<Beneficiaire>();
            this.Beneficiaire11 = new HashSet<Beneficiaire>();
            this.Beneficiaire12 = new HashSet<Beneficiaire>();
            this.Beneficiaire13 = new HashSet<Beneficiaire>();
            this.Beneficiaire14 = new HashSet<Beneficiaire>();
            this.EnqueteEuropasi = new HashSet<EnqueteEuropasi>();
            this.EnqueteEuropasi1 = new HashSet<EnqueteEuropasi>();
            this.EnqueteEuropasi2 = new HashSet<EnqueteEuropasi>();
            this.EnqueteEuropasi3 = new HashSet<EnqueteEuropasi>();
            this.EnqueteEuropasi4 = new HashSet<EnqueteEuropasi>();
            this.EnqueteEuropasi5 = new HashSet<EnqueteEuropasi>();
            this.EnqueteEuropasi6 = new HashSet<EnqueteEuropasi>();
            this.EnqueteEuropasi7 = new HashSet<EnqueteEuropasi>();
        }
    
        public int IDAxePsy { get; set; }
        public string Code { get; set; }
        public string Valeur { get; set; }
    
        public virtual ICollection<Beneficiaire> Beneficiaire { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire1 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire2 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire3 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire4 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire5 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire6 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire7 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire8 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire9 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire10 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire11 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire12 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire13 { get; set; }
        public virtual ICollection<Beneficiaire> Beneficiaire14 { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi1 { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi2 { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi3 { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi4 { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi5 { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi6 { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi7 { get; set; }
    }
}
