//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaireMaisonJustice
    {
        public int IDBeneficiaireMaisonJustice { get; set; }
        public int IDMaisonJustice { get; set; }
        public int IDBeneficiare { get; set; }
        public string NomAssistantJustice { get; set; }
        public string PrenonAssistantJustice { get; set; }
        public string Adresse1AssistantJustice { get; set; }
        public string Adresse2AssistantJustice { get; set; }
        public string CPAssistantJustice { get; set; }
        public string LocaliteAssistantJustice { get; set; }
        public string TelephoneAssistantJustice { get; set; }
        public string FaxAssistantJustice { get; set; }
        public string MailAssistantJustice { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual MaisonJustice MaisonJustice { get; set; }
    }
}
