//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaireMedecin
    {
        public int IDBeneficiaireMedecin { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
        public Nullable<int> IDMedecin { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual Medecin Medecin { get; set; }
    }
}
