//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaireProgramme
    {
        public int IDBeneficiaireProgramme { get; set; }
        public Nullable<int> IDProgramme { get; set; }
        public Nullable<int> IDBeneficiaire { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IDAssistantSocial { get; set; }
        public Nullable<int> IDEducateur { get; set; }
        public Nullable<bool> Horus { get; set; }
        public string Commentaires { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
    
        public virtual AssistantSocial AssistantSocial { get; set; }
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual Educateur Educateur { get; set; }
        public virtual Programme Programme { get; set; }
    }
}
