//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    using Trempoline.Helpers;
    public partial class Beneficiaire
    {
        public Beneficiaire()
        {
            this.Action = new HashSet<Action>();
            this.AdresseBeneficiaire = new HashSet<AdresseBeneficiaire>();
            this.BeneficiaireAvocat = new HashSet<BeneficiaireAvocat>();
            this.BeneficiaireMaisonJustice = new HashSet<BeneficiaireMaisonJustice>();
            this.BeneficiaireMedecin = new HashSet<BeneficiaireMedecin>();
            this.BeneficiaireProgramme = new HashSet<BeneficiaireProgramme>();
            this.EnfantKangourou = new HashSet<EnfantKangourou>();
            this.EnqueteEuropasi = new HashSet<EnqueteEuropasi>();
            this.Fratrie = new HashSet<Fratrie>();
            this.IntervenantFamilial = new HashSet<IntervenantFamilial>();
            this.Participation = new HashSet<Participation>();
            this.Presentiel = new HashSet<Presentiel>();
            this.Sejour = new HashSet<Sejour>();
            this.PieceJointe = new HashSet<PieceJointe>();
        }
    
        public int IDBeneficiare { get; set; }
        private string _Nom;
        public string Nom
        {
            get { return _Nom.Trimmed(); }
            set { _Nom = value; }
        }
        private string _Prenom;
        public string Prenom
        {
            get { return _Prenom.Trimmed(); }
            set { _Prenom = value; }
        }
        private string _Photo;
        public string Photo
        {
            get { return _Photo.Trimmed(); }
            set { _Photo = value; }
        }
        private string _LieuNaissance;
        public string LieuNaissance
        {
            get { return _LieuNaissance.Trimmed(); }
            set { _LieuNaissance = value; }
        }
        public System.DateTime DateNaissance { get; set; }
        private string _RegistreNational;
        public string RegistreNational
        {
            get { return _RegistreNational.Trimmed(); }
            set { _RegistreNational = value; }
        }
        private string _CarteIdentite;
        public string CarteIdentite
        {
            get { return _CarteIdentite.Trimmed(); }
            set { _CarteIdentite = value; }
        }
        public Nullable<int> IDNationalite { get; set; }
        public Nullable<bool> PermisConduire { get; set; }
        public Nullable<System.DateTime> DatePermisConduire { get; set; }
        private string _CommentairesFicheContact;
        public string CommentairesFicheContact
        {
            get { return _CommentairesFicheContact.Trimmed(); }
            set { _CommentairesFicheContact = value; }
        }
        public Nullable<int> IDMutuelle { get; set; }
        public string N_InscriptionMutuelle { get; set; }
        public string RegimeMutuelle { get; set; }
        public Nullable<int> IDRegime { get; set; }
        public string MedecinConseil { get; set; }
        public string CommentairesMututelle { get; set; }
        public Nullable<int> IDCPAS { get; set; }
        public string PersonneContactCPAS { get; set; }
        public string N_TelContactCPAS { get; set; }
        public string CommentairesCPAS { get; set; }
        public Nullable<double> RevenusCPAS { get; set; }
        public Nullable<System.DateTime> DateDebutRevenuCPAS { get; set; }
        public Nullable<double> RevenusIITMutuelle { get; set; }
        public Nullable<System.DateTime> DateDebutRevenuIITMutuelle { get; set; }
        public Nullable<double> RevenusAllocHandic { get; set; }
        public Nullable<double> MontantPensionAlim { get; set; }
        public Nullable<double> AutresRevenus { get; set; }
        public string CommentairesRevenus { get; set; }
        public Nullable<int> IDTypePriseEnCharge { get; set; }
        public Nullable<int> IDEducateur { get; set; }
        public string BanqueCompteVue { get; set; }
        public string NoCompteVue { get; set; }
        public string BanqueCompteEpargne { get; set; }
        public string NoCompteEpargne { get; set; }
        public Nullable<bool> CarteBanque { get; set; }
        public Nullable<bool> CodePin { get; set; }
        public Nullable<bool> PCBanking { get; set; }
        public Nullable<double> SoldeCompteVue { get; set; }
        public Nullable<System.DateTime> DateSoldeCompteVue { get; set; }
        public Nullable<double> SoldeCompteEpargne { get; set; }
        public Nullable<System.DateTime> DateSoldeCompteEpargne { get; set; }
        public Nullable<bool> CompteTrempoline { get; set; }
        public string FichierCompte { get; set; }
        public string CommentairesFinances { get; set; }
        public Nullable<bool> Dettes { get; set; }
        public string CommentairesDettes { get; set; }
        public Nullable<bool> RèglementDettes { get; set; }
        public string AdministrateurBiens { get; set; }
        public string Adresse1AdminBien { get; set; }
        public string Adresse2AdminBien { get; set; }
        public string CPAdminBien { get; set; }
        public string LocaliteAdminBien { get; set; }
        public string TelephoneAdminBien { get; set; }
        public string FaxAdminBien { get; set; }
        public string MailAdminBien { get; set; }
        public Nullable<bool> LiberteConditionnelle { get; set; }
        public Nullable<bool> MediationPenale { get; set; }
        public Nullable<bool> MJA { get; set; }
        public Nullable<bool> Sursis { get; set; }
        public Nullable<bool> MesureDefenseSociale { get; set; }
        public Nullable<bool> OrdonnanceJugeJeunesse { get; set; }
        public string Autre { get; set; }
        public Nullable<System.DateTime> DateDebutLiberteConditionnelle { get; set; }
        public Nullable<System.DateTime> DateDebutMediationPenale { get; set; }
        public Nullable<System.DateTime> DateDebutMJA { get; set; }
        public Nullable<System.DateTime> DateDebutSursis { get; set; }
        public Nullable<System.DateTime> DateDebutMesureDefenseSociale { get; set; }
        public Nullable<System.DateTime> DateDebutOrdonnaceJugeJeunesse { get; set; }
        public Nullable<System.DateTime> DateDebutAutre { get; set; }
        public Nullable<System.DateTime> DateLiberteConditionnelle { get; set; }
        public Nullable<System.DateTime> DateMediationPenale { get; set; }
        public Nullable<System.DateTime> DateMAJ { get; set; }
        public Nullable<System.DateTime> DateSursis { get; set; }
        public Nullable<System.DateTime> DateMesureDefenseSociale { get; set; }
        public Nullable<System.DateTime> DateOrdonnanceJugeJeunsesse { get; set; }
        public Nullable<System.DateTime> DateAutre { get; set; }
        public Nullable<bool> ObligationTrempoline { get; set; }
        public string CommentairesSituationPenale { get; set; }
        public string CommentairesSuiviJudiciaire { get; set; }
        public string SituationCivilPolice { get; set; }
        public Nullable<bool> Enfants { get; set; }
        public Nullable<int> NbreFilles { get; set; }
        public Nullable<int> NbreGarçons { get; set; }
        public Nullable<bool> ContactEffectif { get; set; }
        public Nullable<bool> Jugement { get; set; }
        public string Intervenants { get; set; }
        public Nullable<bool> RCFamiliale { get; set; }
        public Nullable<bool> PensionAlim { get; set; }
        public Nullable<double> MontantPension { get; set; }
        public string NomEmployeur { get; set; }
        public string PrenomEmployeur { get; set; }
        public string Adresse1Employeur { get; set; }
        public string Adresse2Employeur { get; set; }
        public string CPEmployeur { get; set; }
        public string LocaliteEmployeur { get; set; }
        public string TelephoneEmployeur { get; set; }
        public string CommentairesEmployeur { get; set; }
        public string BureauONEMNom { get; set; }
        public string Adresse1ONEM { get; set; }
        public string Adresse2ONEM { get; set; }
        public Nullable<int> CPONEM { get; set; }
        public string LocaliteONEM { get; set; }
        public string TelephoneONEM { get; set; }
        public string FaxONEM { get; set; }
        public string MailONEM { get; set; }
        public Nullable<System.DateTime> DateDebutONEM { get; set; }
        public Nullable<System.DateTime> DateFinONEM { get; set; }
        public string CommentairesONEM { get; set; }
        public string SyndicatNom { get; set; }
        public string Adresse1Syndicat { get; set; }
        public string Adresse2Syndicat { get; set; }
        public Nullable<int> CPSyndicat { get; set; }
        public string LocaliteSyndicat { get; set; }
        public string TelephoneSyndicat { get; set; }
        public string FaxSyndicat { get; set; }
        public string MailSyndicat { get; set; }
        public Nullable<System.DateTime> DateDebutSyndicat { get; set; }
        public Nullable<System.DateTime> DateFinSyndicat { get; set; }
        public string PespectivesRS { get; set; }
        public string CommentairesSyndicat { get; set; }
        public Nullable<int> IDSexe { get; set; }
        public string SituationEntree { get; set; }
        public string Medicaments { get; set; }
        public string CommentairesSuiviMedical { get; set; }
        public Nullable<bool> ParticipationParentGroupeSolidarite { get; set; }
        public Nullable<bool> ParticipationParentMultifamilial { get; set; }
        public Nullable<System.DateTime> DateExamenMedical { get; set; }
        public Nullable<int> NeccesiteSuivi { get; set; }
        public Nullable<int> AXE1DSMA { get; set; }
        public Nullable<int> AXE1DSMB { get; set; }
        public Nullable<int> AXE1TOXA { get; set; }
        public Nullable<int> AXE1TOXB { get; set; }
        public Nullable<int> AXE1TOXC { get; set; }
        public Nullable<int> AXE2A { get; set; }
        public Nullable<int> AXE2B { get; set; }
        public Nullable<int> IndiceGravite { get; set; }
        public Nullable<int> CodeChangement { get; set; }
        public Nullable<int> TraitPrescritA { get; set; }
        public Nullable<int> TraitPrescritB { get; set; }
        public Nullable<int> AutresTraitements { get; set; }
        public Nullable<int> TherapieAssocieeNbre { get; set; }
        public Nullable<int> IncapaciteCEB { get; set; }
        public Nullable<int> NecessiteEtape { get; set; }
        public Nullable<bool> ServiceKangourou { get; set; }
        public Nullable<bool> SuiviFamilial { get; set; }
        public string SuiviIndividuel { get; set; }
        public string CommentairesFamille { get; set; }
        public string OservationsFamille { get; set; }
        public string HistoireFamille { get; set; }
        public string CommentairesGroupeSolidarite { get; set; }
        public Nullable<int> IDDiplome { get; set; }
        public string FormationSuivie { get; set; }
    
        public virtual ICollection<Action> Action { get; set; }
        public virtual ICollection<AdresseBeneficiaire> AdresseBeneficiaire { get; set; }
        public virtual AxePsy AxePsy { get; set; }
        public virtual AxePsy AxePsy1 { get; set; }
        public virtual AxePsy AxePsy2 { get; set; }
        public virtual AxePsy AxePsy3 { get; set; }
        public virtual AxePsy AxePsy4 { get; set; }
        public virtual AxePsy AxePsy5 { get; set; }
        public virtual AxePsy AxePsy6 { get; set; }
        public virtual AxePsy AxePsy7 { get; set; }
        public virtual AxePsy AxePsy8 { get; set; }
        public virtual AxePsy AxePsy9 { get; set; }
        public virtual AxePsy AxePsy10 { get; set; }
        public virtual AxePsy AxePsy11 { get; set; }
        public virtual AxePsy AxePsy12 { get; set; }
        public virtual AxePsy AxePsy13 { get; set; }
        public virtual AxePsy AxePsy14 { get; set; }
        public virtual ICollection<BeneficiaireAvocat> BeneficiaireAvocat { get; set; }
        public virtual ICollection<BeneficiaireMaisonJustice> BeneficiaireMaisonJustice { get; set; }
        public virtual ICollection<BeneficiaireMedecin> BeneficiaireMedecin { get; set; }
        public virtual ICollection<BeneficiaireProgramme> BeneficiaireProgramme { get; set; }
        public virtual ICollection<EnfantKangourou> EnfantKangourou { get; set; }
        public virtual ICollection<EnqueteEuropasi> EnqueteEuropasi { get; set; }
        public virtual ICollection<Fratrie> Fratrie { get; set; }
        public virtual ICollection<IntervenantFamilial> IntervenantFamilial { get; set; }
        public virtual ICollection<Participation> Participation { get; set; }
        public virtual ICollection<Presentiel> Presentiel { get; set; }
        public virtual ICollection<Sejour> Sejour { get; set; }
        public virtual CPAS CPAS { get; set; }
        public virtual Diplome Diplome { get; set; }
        public virtual Educateur Educateur { get; set; }
        public virtual Mutuelle Mutuelle { get; set; }
        public virtual Nationalite Nationalite { get; set; }
        public virtual RegimeMutuelle RegimeMutuelle1 { get; set; }
        public virtual Sexe Sexe { get; set; }
        public virtual TypePriseEnCharge TypePriseEnCharge { get; set; }
        public virtual ICollection<PieceJointe> PieceJointe { get; set; }
    }
}
