//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfantKangourou
    {
        public int IDEnfantKangourou { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime DateNaissanceEK { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
        public Nullable<int> IDAutoriteparentale { get; set; }
        public string AdresseEcole { get; set; }
        public string Adresse1Ecole { get; set; }
        public string Adresse2Ecole { get; set; }
        public string LocaliteEcole { get; set; }
        public string CPEcole { get; set; }
        public string TelEcole { get; set; }
        public string GarantExterieur { get; set; }
        public string Adresse1GarantExterieur { get; set; }
        public string Adresse2GarantExterieur { get; set; }
        public string LocaliteGarantExterieur { get; set; }
        public string CPGarantExterieur { get; set; }
        public string TelephoneGarantExterieur { get; set; }
        public string GSMGarantExterieur { get; set; }
        public string CommentairesSUiviMedical { get; set; }
        public Nullable<bool> SAJ { get; set; }
        public Nullable<bool> SPJ { get; set; }
        public string Commentaires { get; set; }
        public string PriseEnCharge { get; set; }
        public string Adresse1PriseEnCharge { get; set; }
        public string Adresse2PriseEnCharge { get; set; }
        public string LocalitePriseEnCharge { get; set; }
        public string CPPriseEnCharge { get; set; }
        public string TelephonePriseEnCharge { get; set; }
        public string GSMPriseEnCharge { get; set; }
        public Nullable<bool> DansLeService { get; set; }
        public Nullable<bool> AutoriteParentale { get; set; }
    
        public virtual AutoriteParentale AutoriteParentale1 { get; set; }
        public virtual Beneficiaire Beneficiaire { get; set; }
    }
}
