//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnqueteEuropasi
    {
        public string IDEnqueteEuropasi { get; set; }
        public Nullable<int> TypeQuestionnaire { get; set; }
        public Nullable<System.DateTime> DatePassage { get; set; }
        public Nullable<int> SanteMentalePhysique { get; set; }
        public Nullable<int> SituationEmploi { get; set; }
        public Nullable<int> Alcool { get; set; }
        public Nullable<int> Drogues { get; set; }
        public Nullable<int> SituationJudiciaire { get; set; }
        public Nullable<int> DomaineFamilial { get; set; }
        public Nullable<int> EtatPsychologique { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
    
        public virtual AxePsy AxePsy { get; set; }
        public virtual AxePsy AxePsy1 { get; set; }
        public virtual AxePsy AxePsy2 { get; set; }
        public virtual AxePsy AxePsy3 { get; set; }
        public virtual AxePsy AxePsy4 { get; set; }
        public virtual AxePsy AxePsy5 { get; set; }
        public virtual AxePsy AxePsy6 { get; set; }
        public virtual AxePsy AxePsy7 { get; set; }
        public virtual Beneficiaire Beneficiaire { get; set; }
    }
}
