//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fratrie
    {
        public int IDFratrie { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> IDTypeFratrie { get; set; }
        public string Commentaires { get; set; }
        public Nullable<bool> Vivant { get; set; }
        public string Profession { get; set; }
        public Nullable<bool> AlcoolF { get; set; }
        public Nullable<bool> Drogue { get; set; }
        public Nullable<bool> Jeux { get; set; }
        public Nullable<bool> ProbJustice { get; set; }
        public Nullable<bool> Psychiatrique { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
        public Nullable<System.DateTime> FratrieDateNaissance { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual TypeFratrie TypeFratrie { get; set; }
    }
}
