//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localite
    {
        public Localite()
        {
            this.Adresse = new HashSet<Adresse>();
        }
    
        public int IDLocalite { get; set; }
        public string LocaliteNom { get; set; }
        public int CodePostal { get; set; }
    
        public virtual ICollection<Adresse> Adresse { get; set; }
    }
}
