//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medecin
    {
        public Medecin()
        {
            this.BeneficiaireMedecin = new HashSet<BeneficiaireMedecin>();
        }
    
        public int IDMedecin { get; set; }
        public string MedecinNom { get; set; }
        public string MedecinPrenom { get; set; }
        public string MedecinAdresse1 { get; set; }
        public string MedecinAdresse2 { get; set; }
        public Nullable<int> MedecinCP { get; set; }
        public string MedecinLocalite { get; set; }
        public string MedecinTelephone { get; set; }
        public string MedecinFax { get; set; }
        public string MedecinEmail { get; set; }
        public string Specialite { get; set; }
        public string CommentairesMedecin { get; set; }
    
        public virtual ICollection<BeneficiaireMedecin> BeneficiaireMedecin { get; set; }
    }
}
