//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mutuelle
    {
        public Mutuelle()
        {
            this.Beneficiaire = new HashSet<Beneficiaire>();
        }
    
        public int IDMutuelle { get; set; }
        public int Numero { get; set; }
        public string Nom { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public Nullable<int> CodePostal { get; set; }
        public string Localite { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string SiteInternet { get; set; }
        public string Fax { get; set; }
        public string Commentaires { get; set; }
    
        public virtual ICollection<Beneficiaire> Beneficiaire { get; set; }
    }
}
