//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentiel
    {
        public int IDPresentiel { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> HeureDepart { get; set; }
        public Nullable<System.DateTime> HeureArrivee { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
        public Nullable<int> IDTypePresence { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual TypePresence TypePresence { get; set; }
    }
}
