//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sejour
    {
        public int IDSejour { get; set; }
        public System.DateTime DateEntree { get; set; }
        public Nullable<System.DateTime> HeureEntree { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public Nullable<System.DateTime> HeureSortie { get; set; }
        public string Commentaires { get; set; }
        public Nullable<int> IDBeneficiare { get; set; }
        public Nullable<System.DateTime> DateDebutConvention { get; set; }
        public Nullable<System.DateTime> DateFinConvention { get; set; }
        public string ReferenceConvention { get; set; }
        public Nullable<bool> Prolongation { get; set; }
        public Nullable<System.DateTime> DateFinProlongation { get; set; }
        public string EtatAccordMutualiste { get; set; }
        public Nullable<System.DateTime> DateDebutAccord { get; set; }
        public Nullable<System.DateTime> DateFinAccord { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
    }
}
