//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrempolineEntities : DbContext
    {
        public TrempolineEntities()
            : base("name=TrempolineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Action { get; set; }
        public DbSet<Adresse> Adresse { get; set; }
        public DbSet<AdresseBeneficiaire> AdresseBeneficiaire { get; set; }
        public DbSet<AssistantSocial> AssistantSocial { get; set; }
        public DbSet<AtelierFSE> AtelierFSE { get; set; }
        public DbSet<AutoriteParentale> AutoriteParentale { get; set; }
        public DbSet<Avocat> Avocat { get; set; }
        public DbSet<AxePsy> AxePsy { get; set; }
        public DbSet<Beneficiaire> Beneficiaire { get; set; }
        public DbSet<BeneficiaireAvocat> BeneficiaireAvocat { get; set; }
        public DbSet<BeneficiaireMaisonJustice> BeneficiaireMaisonJustice { get; set; }
        public DbSet<BeneficiaireMedecin> BeneficiaireMedecin { get; set; }
        public DbSet<BeneficiaireProgramme> BeneficiaireProgramme { get; set; }
        public DbSet<CPAS> CPAS { get; set; }
        public DbSet<Diplome> Diplome { get; set; }
        public DbSet<Educateur> Educateur { get; set; }
        public DbSet<EnfantKangourou> EnfantKangourou { get; set; }
        public DbSet<EnqueteEuropasi> EnqueteEuropasi { get; set; }
        public DbSet<Fratrie> Fratrie { get; set; }
        public DbSet<IntervenantFamilial> IntervenantFamilial { get; set; }
        public DbSet<Localite> Localite { get; set; }
        public DbSet<MaisonJustice> MaisonJustice { get; set; }
        public DbSet<Medecin> Medecin { get; set; }
        public DbSet<Mutuelle> Mutuelle { get; set; }
        public DbSet<Nationalite> Nationalite { get; set; }
        public DbSet<Participation> Participation { get; set; }
        public DbSet<PieceJointe> PieceJointe { get; set; }
        public DbSet<Presentiel> Presentiel { get; set; }
        public DbSet<Programme> Programme { get; set; }
        public DbSet<RegimeMutuelle> RegimeMutuelle { get; set; }
        public DbSet<Sejour> Sejour { get; set; }
        public DbSet<Sexe> Sexe { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TypeAction> TypeAction { get; set; }
        public DbSet<TypeAdresse> TypeAdresse { get; set; }
        public DbSet<TypeFratrie> TypeFratrie { get; set; }
        public DbSet<TypePresence> TypePresence { get; set; }
        public DbSet<TypePriseEnCharge> TypePriseEnCharge { get; set; }
        public DbSet<User> User { get; set; }
    }
}
