//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trempoline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Action = new HashSet<Action>();
            this.AssistantSocial = new HashSet<AssistantSocial>();
            this.Educateur = new HashSet<Educateur>();
        }
    
        public int IDUser { get; set; }
        public string UserAD { get; set; }
    
        public virtual ICollection<Action> Action { get; set; }
        public virtual ICollection<AssistantSocial> AssistantSocial { get; set; }
        public virtual ICollection<Educateur> Educateur { get; set; }
    }
}
